title: Beautiful Nepal
email: c2edevofficial@gmail.com
year: 2023
prerelease:
  version: "v0.1-alpha.1"
description: |-
  Coding "Beautiful Nepal" on the Web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beautifulnepal.org"
asset_base_url: /assets

google_analytics: "G-7GDYFRE9Y8"

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

github:
 username: beautifulnepal
 url: https://github.com/beautifulnepal/beautifulnepal.org/releases/tag/v0.1-alpha.1
facebook:
 username: btfulnepal

# Pagination settings
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
