title: Beautiful Nepal
email: c2edevofficial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Beautifying Nepal digitally in Web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beautifulnepal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
asset_base_url: /assets

google_analytics: # your google analytics id

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

# Pagination settings
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
